current: darwin_altpackage

clean:
	-rm -Rf installroot *~

darwin_altpackage: 
	test -d installroot/Help || mkdir -p installroot/Help
	cp *.pd installroot/Help
	open darwin_altpackage.pmsp

