<form action="http://pd.klingt.org/webring/" method="post">
<input type="hidden" name="base_url" value="">
<input type="hidden" name="description" value="CVS Repository at SourceForge">

<table width=260 cellpadding=0 cellspacing=0 border=0 bgcolor="#FFFFFF">
  <tr>
    <td width=55 height=25 align="center">
      <input type="image" name="next" src="http://pd.klingt.org/webring/next.gif" align="middle"></td>      
    <td width=62 height=25 align="center">
      <input type="image" name="list" src="http://pd.klingt.org/webring/list.gif" align="middle"></td>
    <td width=63 height=25 align="center">
      <input type="image" name="random" src="http://pd.klingt.org/webring/random.gif" align="middle"></td>
    <td width=80 height=25 align="center">
      <input type="image" name="previous" src="http://pd.klingt.org/webring/previous.gif" align="middle"></td>
  </tr>
  <tr>
    <td colspan=4 width=260 height=50 align="center">
      <a href="http://pd.klingt.org/webring/info.html">
      <img src="http://pd.klingt.org/webring/webring.gif" border=0 width=260
      height=50 align="middle" alt="pd webring"></a>
    </td>
  </tr>
</table>
</form>
