#!/bin/sh
# update from the local CVS repository

# the source dir where this script is
SCRIPT_DIR=`echo $0 | sed 's|\(.*\)/.*$|\1|'`
. $SCRIPT_DIR/auto-build-common

# the name of this script
SCRIPT=`echo $0| sed 's|.*/\(.*\)|\1|g'`
LOGFILE=/home/pd/logs/${DATE}_${TIME}_-_${SCRIPT}_-_${SYSTEM}.txt

update_distro ()
{
	 distro=$1
	 echo "------------------------------------------------------------"	>> $LOGFILE 2>&1
	 echo "$distro"	>> $LOGFILE 2>&1
	 echo "------------------------------------------------------------"	>> $LOGFILE 2>&1
	 /home/pd/rsync/$distro/scripts/update-developer-layout.sh >> $LOGFILE 2>&1
}

touch $LOGFILE

update_distro pd-extended
update_distro pd-extended-release
update_distro pd-main
update_distro pd-devel
