#!/bin/sh

SYSTEM=`uname -s`
DATE=`date +%Y-%m-%d`
TIME=`date +%H.%M.%S`
SCRIPT=`echo $0| sed 's|.*/\(.*\)|\1|g'`
LOGFILE=/home/pd/logs/${DATE}_${TIME}_-_${SCRIPT}_-_${SYSTEM}.txt

touch $LOGFILE

# extended
echo "------------------------------------------------------------"	>> $LOGFILE 2>&1
echo "pd-extended"	>> $LOGFILE 2>&1
echo "------------------------------------------------------------"	>> $LOGFILE 2>&1
su pd -c "/home/pd/rsync/pd-extended/scripts/update-developer-layout.sh" >> $LOGFILE 2>&1

# devel
echo "------------------------------------------------------------"	>> $LOGFILE 2>&1
echo "pd-devel"	>> $LOGFILE 2>&1
echo "------------------------------------------------------------"	>> $LOGFILE 2>&1
su pd -c "cd /home/pd/rsync/pd-devel/pd && cvs up -Pd" >> $LOGFILE 2>&1
su pd -c "/home/pd/rsync/pd-extended/scripts/update-developer-layout.sh" >> $LOGFILE 2>&1

# main
echo "------------------------------------------------------------"	>> $LOGFILE 2>&1
echo "pd-main"	>> $LOGFILE 2>&1
echo "------------------------------------------------------------"	>> $LOGFILE 2>&1
su pd -c "cd /home/pd/rsync/pd-main/pd && cvs up -APd" >> $LOGFILE 2>&1
