#!/bin/sh

HOSTNAME=`hostname`
SYSTEM=`uname -s`
DATE=`date +%Y-%m-%d`
TIME=`date +%H.%M.%S`
SCRIPT=`echo $0| sed 's|.*/\(.*\)|\1|g'`

run_build_script ()
{
	 distro=$1

	 LOGFILE=/home/pd/logs/${DATE}_${TIME}_-_${SYSTEM}_-_${distro}_-_${SCRIPT}.txt
	 touch ${LOGFILE} 

	 su pd -c "sh /home/pd/auto-build/${distro}/scripts/auto-build/${distro}-auto-builder.sh" >> $LOGFILE 2>&1

# send status report
	 SUBJECT="$HOSTNAME Pd-$SYSTEM $distro build results $DATE $TIME"
	 tail -200 ${LOGFILE} | mail -s "${SUBJECT}" hans@eds.org
}

run_build_script pd-main
run_build_script pd-extended
#run_build_script pd-devel


